id = "jsp"
name = "JSP"
description = "JSP (JavaServer Pages) support"
version = "0.1.0"
schema_version = 1
authors = ["Your Name <your.email@example.com>"]
repository = "https://github.com/your-username/jsp"

languages = ["jsp"]

[language_servers.jsp-language-server]
name = "JSP Language Server"
language = "JSP"

[grammars.html]
repository = "https://github.com/tree-sitter/tree-sitter-html"
commit = "bfa075d83c6b97cd48440b3829ab8d24a2319809"
