id = "jsp"
name = "JSP"
description = "JSP (JavaServer Pages) support"
version = "0.2.7"
schema_version = 1
authors = ["Your Name <your.email@example.com>"]
repository = "https://github.com/your-username/jsp"

[language_servers.jsp-language-server]
name = "JSP Language Server"
language = "JSP"

[grammars.html]
repository = "https://github.com/tree-sitter/tree-sitter-html"
rev = "29f53d8f4f2335e61bf6418ab8958dac3282077a"               # A known working commit
